/*
  Warnings:

  - Made the column `IDDEP` on table `TBAVA008` required. This step will fail if there are existing NULL values in that column.
  - Made the column `TIPO` on table `TBAVA010` required. This step will fail if there are existing NULL values in that column.
  - Made the column `IDRECURSO` on table `TBAVA011` required. This step will fail if there are existing NULL values in that column.
  - Made the column `FIMRESERVA` on table `TBAVA011` required. This step will fail if there are existing NULL values in that column.
  - Made the column `IDCOLABORADOR` on table `TBAVA011` required. This step will fail if there are existing NULL values in that column.
  - Made the column `INIRESERVA` on table `TBAVA011` required. This step will fail if there are existing NULL values in that column.

*/
BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[TBAVA008] DROP CONSTRAINT [TBAVA008_IDDEP_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[TBAVA010] DROP CONSTRAINT [TBAVA010_TIPO_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[TBAVA011] DROP CONSTRAINT [TBAVA011_IDCOLABORADOR_fkey];

-- DropForeignKey
ALTER TABLE [dbo].[TBAVA011] DROP CONSTRAINT [TBAVA011_IDRECURSO_fkey];

-- AlterTable
ALTER TABLE [dbo].[TBAVA008] ALTER COLUMN [IDDEP] NVARCHAR(1000) NOT NULL;

-- AlterTable
ALTER TABLE [dbo].[TBAVA010] ALTER COLUMN [TIPO] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[TBAVA010] ALTER COLUMN [STATUS] BIT NULL;

-- AlterTable
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [OBSERVACAO] VARCHAR(80) NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [IDRECURSO] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [FIMRESERVA] DATETIME2 NOT NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [IDCOLABORADOR] INT NOT NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [INIRESERVA] DATETIME2 NOT NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [STATUS] BIT NULL;
ALTER TABLE [dbo].[TBAVA011] ALTER COLUMN [TEMPOEMMINUTOS] INT NULL;
ALTER TABLE [dbo].[TBAVA011] ADD CONSTRAINT [TBAVA011_STATUS_df] DEFAULT 0 FOR [STATUS];

-- CreateTable
CREATE TABLE [dbo].[TBAVA013] (
    [IDPUBLICACAO] NVARCHAR(1000) NOT NULL,
    [TEXTO] NVARCHAR(1000),
    [DATAPUBLICACAO] DATETIME2 NOT NULL,
    [LIKES] INT,
    [IDCOLABORADOR] INT NOT NULL,
    [arquivo] NVARCHAR(1000),
    CONSTRAINT [TBAVA013_pkey] PRIMARY KEY CLUSTERED ([IDPUBLICACAO])
);

-- CreateTable
CREATE TABLE [dbo].[TBAVA014] (
    [IDCURTIDA] NVARCHAR(1000) NOT NULL,
    [IDCOLABORADOR] INT NOT NULL,
    [IDPUBLI] NVARCHAR(1000) NOT NULL,
    [Curtida] INT NOT NULL CONSTRAINT [TBAVA014_Curtida_df] DEFAULT 1,
    CONSTRAINT [TBAVA014_pkey] PRIMARY KEY CLUSTERED ([IDCURTIDA])
);

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA008] ADD CONSTRAINT [TBAVA008_IDDEP_fkey] FOREIGN KEY ([IDDEP]) REFERENCES [dbo].[TBAVA007]([IDDEP]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA010] ADD CONSTRAINT [TBAVA010_TIPO_fkey] FOREIGN KEY ([TIPO]) REFERENCES [dbo].[TBAVA009]([IDTIPORECURSO]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA011] ADD CONSTRAINT [TBAVA011_IDRECURSO_fkey] FOREIGN KEY ([IDRECURSO]) REFERENCES [dbo].[TBAVA010]([IDRECURSO]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA011] ADD CONSTRAINT [TBAVA011_IDCOLABORADOR_fkey] FOREIGN KEY ([IDCOLABORADOR]) REFERENCES [dbo].[TBAVA001]([IDCOL]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA013] ADD CONSTRAINT [TBAVA013_IDCOLABORADOR_fkey] FOREIGN KEY ([IDCOLABORADOR]) REFERENCES [dbo].[TBAVA001]([IDCOL]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA014] ADD CONSTRAINT [TBAVA014_IDCOLABORADOR_fkey] FOREIGN KEY ([IDCOLABORADOR]) REFERENCES [dbo].[TBAVA001]([IDCOL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA014] ADD CONSTRAINT [TBAVA014_IDPUBLI_fkey] FOREIGN KEY ([IDPUBLI]) REFERENCES [dbo].[TBAVA013]([IDPUBLICACAO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
