/*
  Warnings:

  - Added the required column `IDPERUSU` to the `TBAVA004` table without a default value. This is not possible if the table is not empty.

*/
BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[TBAVA004] ADD [IDPERUSU] NVARCHAR(1000) NOT NULL;

-- CreateTable
CREATE TABLE [dbo].[TBAVA009] (
    [IDTIPORECURSO] NVARCHAR(1000) NOT NULL,
    [DESCRICAO] VARCHAR(80) NOT NULL,
    CONSTRAINT [TBAVA009_pkey] PRIMARY KEY CLUSTERED ([IDTIPORECURSO])
);

-- CreateTable
CREATE TABLE [dbo].[TBAVA010] (
    [IDRECURSO] NVARCHAR(1000) NOT NULL,
    [DESCRICAO] VARCHAR(80) NOT NULL,
    [TIPO] VARCHAR(80) NOT NULL,
    [STATUS] BIT NOT NULL CONSTRAINT [TBAVA010_STATUS_df] DEFAULT 0,
    CONSTRAINT [TBAVA010_pkey] PRIMARY KEY CLUSTERED ([IDRECURSO])
);

-- CreateTable
CREATE TABLE [dbo].[TBAVA011] (
    [IDFUNCAO] NVARCHAR(1000) NOT NULL,
    [DESCRICAO] VARCHAR(80) NOT NULL,
    [IDDEP] NVARCHAR(1000),
    CONSTRAINT [TBAVA011_pkey] PRIMARY KEY CLUSTERED ([IDFUNCAO])
);

-- AddForeignKey
ALTER TABLE [dbo].[TBAVA004] ADD CONSTRAINT [TBAVA004_IDPERUSU_fkey] FOREIGN KEY ([IDPERUSU]) REFERENCES [dbo].[TBAVA005]([IDPERUSU]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
